### PR TITLE
Fix memory alignment problem on ARM6 (#1)

### PR DESCRIPTION
**Pull request by breiting**

### CODE REVIEW

**Comment by breiting** [comment]
Any chance to get this in?

**Comment by sachinsh76** [comment]
Hey can you create a pull request on original go client?

**Comment by breiting** [comment]
> Hey can you create a pull request on original go client?

Which one are you referring to?

**Comment by sachinsh76** [comment]
Hey sorry... I meant original gowebeocket GitHub library.

**Comment by sachinsh76** [comment]
I will merge it right away :)

**Pull request closed without merging**
